fix: modified workflow to check access entry

diff --git a/.github/workflows/deploy-platform-tools.yaml b/.github/workflows/deploy-platform-tools.yaml
--- a/.github/workflows/deploy-platform-tools.yaml
+++ b/.github/workflows/deploy-platform-tools.yaml
@@ -41,16 +41,23 @@ jobs:
         uses: azure/setup-helm@v3
         with:
           version: 'v3.13.0'
+      
+      #Install AWS CLI
+      - name: Ensure AWS CLI is installed
+        run: |
+            if ! command -v aws &> /dev/null
+            then
+              echo "AWS CLI not found. Installing..."
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+              unzip -q awscliv2.zip
+              sudo ./aws/install
+            else
+              echo "AWS CLI already installed"
+            fi
 
       # Login to EKS, make sure to switch to the permanent cluster created with terraform once it's up
       - name: Login to EKS - update kubeconfig.
         run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
-      
-      - name: get caller identity
-        run: aws sts get-caller-identity
-      
-      - name: for debugging
-        run: kubectl get pods -A
 
       # Add deployment steps for each tool below
       - name: Deploy ingress-nginx controller
@@ -77,29 +84,33 @@ jobs:
             --namespace helm-system \
             --create-namespace  
 
-      #Install AWS CLI
-      - name: Ensure AWS CLI is installed
+      # Create aws eks access entry
+      - name: Ensure EKS Access Entry
         run: |
-            if ! command -v aws &> /dev/null
-            then
-              echo "AWS CLI not found. Installing..."
-              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-              unzip -q awscliv2.zip
-              sudo ./aws/install
+            set -e  # exit on any error
+
+            ROLE_ARN="arn:aws:iam::383585068161:role/DeveloperProdAccessRole-ubuntu25b"
+
+            if ! aws eks describe-access-entry \
+                --cluster-name "$CLUSTER_NAME" \
+                --principal-arn "$ROLE_ARN" >/dev/null 2>&1; then
+              echo "Access entry not found. Creating..."
+              aws eks create-access-entry \
+                --cluster-name "$CLUSTER_NAME" \
+                --principal-arn "$ROLE_ARN" \
+                --type STANDARD \
+                --kubernetes-groups dev-team \
+                --username DeveloperProdAccessRole
             else
-              echo "AWS CLI already installed"
+              echo "Access entry exists. Updating..."
+              aws eks update-access-entry \
+                --cluster-name "$CLUSTER_NAME" \
+                --principal-arn "$ROLE_ARN" \
+                --type STANDARD \
+                --kubernetes-groups dev-team \
+                --username DeveloperProdAccessRole
             fi
 
-      # Create aws eks access entry
-      - name: Create EKS Access Entry
-        run: |
-          aws eks create-access-entry \
-            --cluster-name $CLUSTER_NAME \
-            --principal-arn arn:aws:iam::383585068161:role/DeveloperProdAccessRole-ubuntu25b \
-            --type STANDARD \
-            --kubernetes-groups dev-team \
-            --username DeveloperProdAccessRole
-      
       # Verify Access Entry 
       - name: Verify Access Entry
         run: |
